name: wallpaper_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.1+10

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  awesome_dialog: ^2.1.1
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.17
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.3
  dots_indicator: ^2.0.0
  ext_storage:
    git:
      url: git://github.com/lavahasif/ext_storage_ups.git
  firebase_auth: ^3.1.2
  firebase_core: ^1.7.0
  flutter:
    sdk: flutter
  flutter_downloader: ^1.7.0
  flutter_launcher_icons: ^0.9.3
  flutter_staggered_grid_view: ^0.4.0
  font_awesome_flutter: ^10.1.0
  google_mobile_ads: ^1.2.0
  google_sign_in: ^5.1.1
  intl: ^0.17.0
  launch_review: ^3.0.1
  onesignal_flutter:
    git:
      url: https://github.com/luis901101/OneSignal-Flutter-SDK.git
      ref: migrate_android_embedding_v2
  path_provider: ^2.0.5
  permission_handler: ^9.2.0
  provider: ^6.0.1
  rounded_loading_button: ^2.0.9
  shared_preferences: ^2.0.8
  shimmer: ^2.0.0
  sliding_up_panel: ^2.0.0+1
  wallpaper: ^1.0.7

dev_dependencies:

  flutter_launcher_icons: "^0.9.2"
  flutter_native_splash: ^2.1.6
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/icon.png"

flutter_native_splash:
  image: assets/images/splash.png
  color: "ffffff"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:

    - assets/images/
    - assets/images/icon.png

  fonts:

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
